config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'predio1'      =>  'static_pages#predio1'
  get 'predio2'      =>  'static_pages#predio2'
  get 'equipamentos' =>  'static_pages#equipamentos'
  get 'cadastro'     =>  'static_pages#cadastro'
  get 'login'        =>  'static_pages#login'
  get 'usuario'      =>  'static_pages#usuario'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def predio1
  end

  def predio2
  end

  def equipamentos
  end

  def cadastro
  end

  def login
  end

  def usuario
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projeto1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "icone">
    <div class="container header-logo-default">
      <%= link_to image_tag("IC-Logo.png", alt: "Rails logo"), root_path%>
    </div>
  </div>
      
  <nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Salas<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Predio 1", predio1_path %></li>
              <li><%= link_to "Predio 2",predio2_path%></li>
            </ul>
          </li>
          <li><%= link_to "Equipamentos",equipamentos_path%></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Login",login_path%></li>
          <li><%= link_to "Cadastro",cadastro_path%></li>
        </ul>
            <!--<form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Busque por sala ou equipamento">
              </div>
              <input type="checkbox" name="tipo-busca" value="sala">Sala                       <input type="checkbox" name="tipo-busca" value="equip">Projetor
              <button type="submit" class="btn btn-default">Procurar</button>
            </form>  -->
        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <div class="input-group">
              <input type="text" class="form-control" aria-label="...">
                <div class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pesquisar por: <span class="caret"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <li><button type="submit" value="sala"class="btn btn-default btn-busca"> Sala </button></li>
                      <li><button type="submit" value="projetor"class="btn btn-default btn-busca">Projetor</li>
                    </ul>
                  </div>
            </form>
                  
                </div><!-- /btn-group -->
              </div><!-- /input-group -->

          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
  </div>
  
  <div class="container">
    <%= yield %>
  </div>
  
  <footer id = "footer">
      <p><br><br> </p>
  </footer>


<script src="js/bootstrap.min.js"></script>
   <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
 
    
    
    <script src='projeto.js'></script>
    -->
</body>
</html>

app/views/static_pages/cadastro.html.erb
<h1>StaticPages#cadastro</h1>
<p>Find me in app/views/static_pages/cadastro.html.erb</p>

app/views/static_pages/equipamentos.html.erb
<h1>StaticPages#equipamentos</h1>
<p>Find me in app/views/static_pages/equipamentos.html.erb</p>

app/views/static_pages/home.html.erb
<section id="sobre">
      <div class="container sobre">
        <h2>BEM-VINDO!</h2>
        <h4>
           Cheque as salas do Instituto da Computação da UFF e os equipamentos disponíveis para reserva aqui. 
          <br>Observações:<br> Não é possivel reservar um projetor e uma sala que já contém o equipamento simultaneamente.
          Alunos devem contatar o gerente caso desejem fazer uma reserva.
        </h4>
      </div>
    </section>

app/views/static_pages/login.html.erb
<h1>StaticPages#login</h1>
<p>Find me in app/views/static_pages/login.html.erb</p>

app/views/static_pages/predio1.html.erb
<h1>StaticPages#predio1</h1>
<p>Find me in app/views/static_pages/predio1.html.erb</p>

app/views/static_pages/predio2.html.erb
<h1>StaticPages#predio2</h1>
<p>Find me in app/views/static_pages/predio2.html.erb</p>

app/views/static_pages/usuario.html.erb
<h1>StaticPages#usuario</h1>
<p>Find me in app/views/static_pages/usuario.html.erb</p>